# Generated by Django 4.2.28 on 2026-02-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
